name: GitHub Actions Demo
on: [push]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: prepare
        run: npm run build
      - name: unit tests
        run: npm run test
